version: 0.2

phases:
  build:
    commands:
      - npm install && ./node_modules/.bin/gulp build

artifacts:
  files:
    - app.js
    - static_server.js
    - dist/*
    - dist/**/*
    - node_modules/*
    - node_modules//**/*
